services:
  backend:
    build: .
    container_name: inkflow-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: inkflow-mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: